#include "btpair.h"
#include "storage.h"
#include "protocol.h"
#include "ui.h"
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEClient.h>
#include <BLEScan.h>
#include <BLEAdvertisedDevice.h>
#include <BLE2902.h>
#include <esp_random.h>

// ===== BLE UUIDs (custom, fixed for this app) =====
#define BTPAIR_SVC_UUID   "6ba2c7f5-1234-4b6f-8d25-7f3c6b4a5e01"
#define BTPAIR_INFO_UUID  "6ba2c7f5-1234-4b6f-8d25-7f3c6b4a5e02"  // READ
#define BTPAIR_ACK_UUID   "6ba2c7f5-1234-4b6f-8d25-7f3c6b4a5e03"  // WRITE
#define BLE_DEVICE_NAME   "LoRaMsg"
#define BTPAIR_TIMEOUT_MS 60000UL
#define BTPAIR_SCAN_SEC   5

// Packet formats (packed, no padding needed — all uint8_t arrays):
//   INFO (HOST→JOIN): id(1) + name(16) + key(32) = 49 bytes
//   ACK  (JOIN→HOST): id(1) + name(16)            = 17 bytes
#define INFO_SIZE 49
#define ACK_SIZE  17

// ===== Module state =====
static BTPairState g_state    = BTPAIR_IDLE;
static uint32_t    g_startMs  = 0;
static char        g_status[48] = "Ready";
static bool        g_bleInited  = false;

static uint8_t g_genKey[32]   = {0};  // key generated by HOST
static Contact g_result;
static volatile bool g_resultReady = false;

// ===== HOST (server) helpers =====
static BLEServer*         g_server   = nullptr;
static BLECharacteristic* g_infoChar = nullptr;
static BLECharacteristic* g_ackChar  = nullptr;

class AckWriteCallback : public BLECharacteristicCallbacks {
  void onWrite(BLECharacteristic* ch) override {
    if (g_state != BTPAIR_HOST) return;
    String v = ch->getValue();
    if ((int)v.length() < ACK_SIZE) return;

    Contact ct{};
    ct.id = (uint8_t)v.charAt(0);
    memcpy(ct.name, v.c_str() + 1, 16);
    ct.name[15] = '\0';
    memcpy(ct.key, g_genKey, 32);

    g_result      = ct;
    g_resultReady = true;
    snprintf(g_status, sizeof(g_status), "Paired: %s", ct.name);
  }
};
static AckWriteCallback g_ackCb;

// ===== JOIN (client/scan) helpers =====
static BLEScan*          g_scan          = nullptr;
static bool              g_scanRunning   = false;
static uint32_t          g_scanEndMs     = 0;   // millis() when current scan window expires
static volatile bool     g_foundTarget   = false;
static String            g_targetAddrStr = "";

class FoundDeviceCallback : public BLEAdvertisedDeviceCallbacks {
  void onResult(BLEAdvertisedDevice adv) override {
    if (g_foundTarget) return;
    if (!adv.haveServiceUUID()) return;
    if (!adv.isAdvertisingService(BLEUUID(BTPAIR_SVC_UUID))) return;
    g_targetAddrStr = String(adv.getAddress().toString().c_str());
    g_foundTarget   = true;
    BLEDevice::getScan()->stop();
    snprintf(g_status, sizeof(g_status), "Found host, connecting...");
  }
};
static FoundDeviceCallback g_foundCb;

// ===== Internal helpers =====
static void bleEnsureInited() {
  if (!g_bleInited) {
    BLEDevice::init(BLE_DEVICE_NAME);
    g_bleInited = true;
  }
}

static void startScan() {
  g_scan = BLEDevice::getScan();
  g_scan->setAdvertisedDeviceCallbacks(&g_foundCb, false);
  g_scan->setActiveScan(true);
  g_scan->setInterval(100);
  g_scan->setWindow(90);
  g_scan->start(BTPAIR_SCAN_SEC, false);  // non-blocking
  g_scanRunning = true;
  g_scanEndMs   = millis() + (BTPAIR_SCAN_SEC * 1000UL) + 500UL; // +500ms margin
}

// Connect to host, read INFO, write ACK. Returns true on success.
static bool doJoinConnect() {
  BLEClient* client = BLEDevice::createClient();

  BLEAddress addr(g_targetAddrStr.c_str());
  if (!client->connect(addr)) {
    snprintf(g_status, sizeof(g_status), "Connect failed, retrying...");
    delete client;
    return false;
  }

  BLERemoteService* svc = client->getService(BLEUUID(BTPAIR_SVC_UUID));
  if (!svc) {
    snprintf(g_status, sizeof(g_status), "Service missing");
    client->disconnect();
    delete client;
    return false;
  }

  BLERemoteCharacteristic* infoC = svc->getCharacteristic(BLEUUID(BTPAIR_INFO_UUID));
  BLERemoteCharacteristic* ackC  = svc->getCharacteristic(BLEUUID(BTPAIR_ACK_UUID));
  if (!infoC || !ackC) {
    snprintf(g_status, sizeof(g_status), "Chars missing");
    client->disconnect();
    delete client;
    return false;
  }

  String info = infoC->readValue();
  if ((int)info.length() < INFO_SIZE) {
    snprintf(g_status, sizeof(g_status), "Bad data from host");
    client->disconnect();
    delete client;
    return false;
  }

  // Parse INFO packet: id(1) | name(16) | key(32)
  Contact ct{};
  ct.id = (uint8_t)info.charAt(0);
  memcpy(ct.name, info.c_str() + 1, 16);
  ct.name[15] = '\0';
  memcpy(ct.key, info.c_str() + 17, 32);

  // Send ACK packet: id(1) | name(16)
  String myName = storageDeviceName();
  uint8_t ackBuf[ACK_SIZE] = {0};
  ackBuf[0] = (uint8_t)protocolDeviceId();
  strncpy((char*)ackBuf + 1, myName.c_str(), 16);
  ackC->writeValue(ackBuf, ACK_SIZE);

  client->disconnect();
  delete client;

  g_result      = ct;
  g_resultReady = true;
  snprintf(g_status, sizeof(g_status), "Paired: %s", ct.name);
  return true;
}

// ===== Public API =====

void btpairStartHost() {
  bleEnsureInited();

  // Generate random 32-byte shared key
  for (int i = 0; i < 32; i++) g_genKey[i] = (uint8_t)(esp_random() & 0xFF);

  // Build INFO packet: id(1) | name(16) | key(32)
  String myName = storageDeviceName();
  uint8_t infoBuf[INFO_SIZE] = {0};
  infoBuf[0] = (uint8_t)protocolDeviceId();
  strncpy((char*)infoBuf + 1, myName.c_str(), 16);
  memcpy(infoBuf + 17, g_genKey, 32);

  // Create GATT server
  g_server = BLEDevice::createServer();
  BLEService* svc = g_server->createService(BTPAIR_SVC_UUID);

  g_infoChar = svc->createCharacteristic(BTPAIR_INFO_UUID, BLECharacteristic::PROPERTY_READ);
  g_infoChar->setValue(infoBuf, INFO_SIZE);

  g_ackChar = svc->createCharacteristic(BTPAIR_ACK_UUID, BLECharacteristic::PROPERTY_WRITE);
  g_ackChar->setCallbacks(&g_ackCb);

  svc->start();

  BLEAdvertising* adv = BLEDevice::getAdvertising();
  adv->addServiceUUID(BTPAIR_SVC_UUID);
  adv->setScanResponse(true);
  BLEDevice::startAdvertising();

  g_resultReady = false;
  g_state       = BTPAIR_HOST;
  g_startMs     = millis();
  snprintf(g_status, sizeof(g_status), "Waiting for device...");
}

void btpairStartJoin() {
  bleEnsureInited();

  g_foundTarget   = false;
  g_targetAddrStr = "";
  g_resultReady   = false;

  startScan();

  g_state   = BTPAIR_JOIN;
  g_startMs = millis();
  snprintf(g_status, sizeof(g_status), "Scanning...");
}

void btpairTick() {
  if (g_state == BTPAIR_IDLE ||
      g_state == BTPAIR_DONE_OK ||
      g_state == BTPAIR_DONE_FAIL) return;

  uint32_t now = millis();

  // Global timeout
  if (now - g_startMs >= BTPAIR_TIMEOUT_MS) {
    btpairStop();
    g_state = BTPAIR_DONE_FAIL;
    snprintf(g_status, sizeof(g_status), "Timeout (60s)");
    if (page == PAGE_BT_PAIR) uiDrawBTPair();
    return;
  }

  // HOST: wait for ACK write callback
  if (g_state == BTPAIR_HOST) {
    if (g_resultReady) {
      storageAddContact(g_result);
      btpairStop();
      g_state = BTPAIR_DONE_OK;
      if (page == PAGE_BT_PAIR) uiDrawBTPair();
    }
    return;
  }

  // JOIN: handle scan → connect flow
  if (g_state == BTPAIR_JOIN) {
    if (g_foundTarget) {
      g_foundTarget = false;
      g_scanRunning = false;
      if (doJoinConnect()) {
        storageAddContact(g_result);
        btpairStop();
        g_state = BTPAIR_DONE_OK;
      } else {
        // Connect failed — restart scan if time permits
        if (now - g_startMs < BTPAIR_TIMEOUT_MS - 6000) {
          startScan();
        }
      }
      if (page == PAGE_BT_PAIR) uiDrawBTPair();
      return;
    }

    // Restart scan when the current window has expired
    if (g_scanRunning && now >= g_scanEndMs) {
      g_scanRunning = false;
      if (now - g_startMs < BTPAIR_TIMEOUT_MS - 6000) {
        snprintf(g_status, sizeof(g_status), "Scanning...");
        startScan();
        if (page == PAGE_BT_PAIR) uiDrawBTPair();
      }
    }
  }
}

void btpairStop() {
  if (g_scan && g_scanRunning) {
    g_scan->stop();
    g_scanRunning = false;
  }
  BLEDevice::stopAdvertising();
  // Leave BLEDevice inited — calling deinit/reinit repeatedly is unsafe
}

void btpairReset() {
  btpairStop();
  g_state       = BTPAIR_IDLE;
  g_resultReady = false;
  g_foundTarget = false;
  snprintf(g_status, sizeof(g_status), "Ready");
}

BTPairState btpairState()  { return g_state; }
const char* btpairStatus() { return g_status; }
